name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        working-directory: packages/next@site
        run: |
          ls
          node -v
          npm install pnpm -g
          pnpm -v
          pnpm install 
          pnpm run generate

      - name: deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzh
          path: packages/next@site/.output/public/
          remote_path: ${{secrets.target}}
          remote_host: ${{secrets.HOST}}
          remote_user: ${{secrets.USER}}
          remote_key: ${{secrets.ACCESS_TOKEN}}